### ISSUE TITLE
Example Metric component hits API 4 times for each request 

### ISSUE THREAD

**Issue by oakley808** [NuCivic/react-dash#32]
In your sample dashboard, the Unique Visitors metric component causes four `fetch()` requests on loading. (instead of just one as I would expect)

This is possibly caused by calling `getData()` within the render method.
https://github.com/NuCivic/react-dashboard/blob/bffd601faa6d1a6325da88ac114ecd500bc4ffad/src/components/Metric.js#L32

Steps to repeat:
1. Install fresh copy of dashboard 
2. Remove all components except the Unique Visitors metric from settings.js and MyCustomLayout.js 
3. Check Devtools console on page load. Screenshot below. 

![screen shot 2016-09-06 at 9 37 57 am](https://cloud.githubusercontent.com/assets/2180632/18280525/88635920-7416-11e6-9993-64686a3fa2ae.png)

**Comment by starsinmypockets** [comment]
The data handling has been significantly refactored in refactor-data-handling branch. This should be released shortly as 0.4.0 

I'm not entirely sure that this specific issue is addressed but I will check!

**Comment by topicus** [comment]
@starsinmypockets Any news about this?

**Comment by starsinmypockets** [comment]
This was fixed in the refactor-data-handling branch which we'll be releasing next week!

**Comment by starsinmypockets** [comment]
This should be resolved in 0.4
