### ISSUE TITLE
applyDataHandlers results in loss of data

### ISSUE THREAD

**Issue by oakley808** [NuCivic/react-dash#34]
If the user receives data from an API that contains a `hits` property, this will fail.
```
  applyDataHandlers(data = [], handlers) {
    let _handlers = handlers || this.state.filterHandlers || this.props.dataHandlers;
    let _data = data.hits || data;   // <--- fails
```
e.g. If the user data/API result is shaped like `{ foo: 1, bar: 2, hits: 'baz' }` then the component will only receive `baz` and the rest will be lost.

https://github.com/NuCivic/react-dash/blob/14f1b31d33fdb61cd61cc0199a43778555ca6a30/src/components/BaseComponent.js#L241

**Comment by starsinmypockets** [comment]
See here https://github.com/NuCivic/react-dash/commit/cc3cf22f1c91f83f31d34030e635af7372ed6340

This should isolate our opinionated code.

**Comment by starsinmypockets** [comment]
fwiw we're working on untangling filtering and fetching code into higher order components
