### ISSUE TITLE
Fix deprecated components and update to React v.16

### ISSUE THREAD

**Issue by iris-i** [NuCivic/react-dash#82]
This warning: warning.js:35 Warning: AutosizeInput: isMounted is deprecated. is caused by using a deprecated pattern, isMounted, instead of ComponentDidMount & ComponentWillUnmount.
Reference: https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

This is mainly used in npm packages which are external libraries being used with React-dash.
Mainly the fixed-data-table , react-input-autosize & react-select packages in the node_modules dir. For these, we should probably file issues in their respective repos.

We are also using isMounted in a react-dash npm package, also in the node_modules folder. Looking at the files I think we may need to restructure the component to use the lifecycle methods (ComponentDidMount) etc. in order to fix this.

**Comment by erogray** [comment]
This ticket is no longer current; will create a new one if needed
