### ISSUE TITLE
Get the React-dash boilerplate working

### ISSUE THREAD

**Issue by iris-i** [NuCivic/react-dash#84]
The boilerplate setup instructions has compile errors. The installation process does not get completed. 
Repo: https://github.com/NuCivic/react-dash-boilerplate

**Comment by iris-i** [comment]
@kimwdavidson this is not urgent. It can probably go in the icebox for now.

**Comment by jagatfx** [comment]
A note in the README mentioning that it is not presently functional / up-to-date would be kind for developers trying out the project

**Comment by erogray** [comment]
Unfortunately our team doesn't have bandwidth to work on this repo — closing since this issue seems unlikely to get addressed.
