### ISSUE TITLE
SPIKE: Implications of supporting CORS in addition to JSONP

### ISSUE THREAD

**Issue by iris-i** [NuCivic/react-dash#85]
Based on a client request. Do we need to enable CORS support in addition to JSONP?
Wikipedia results suggest that JSONP is older and more susceptible to XSS attacks (if the source site is compromised) and some other security concerns.
https://en.wikipedia.org/wiki/JSONP
https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by erogray** [comment]
No longer a current priority for React-dash
